<?php

return [
    //1** => PHP, 2** => Python, 3** => Ruby, 9** => Normal

    //PHP
    101 => [
        'id' => 101,
        'lang' => 'PHP',
        'name' => 'PHP',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    102 => [
        'id' => 102,
        'lang' => 'PHP',
        'name' => 'Symfony',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    103 => [
        'id' => 103,
        'lang' => 'PHP',
        'name' => 'Laravel',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    104 => [
        'id' => 104,
        'lang' => 'PHP',
        'name' => 'CakePHP',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    105 => [
        'id' => 105,
        'lang' => 'PHP',
        'name' => 'FuelPHP',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],
    106 => [
        'id' => 106,
        'lang' => 'PHP',
        'name' => 'WordPress',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    107 => [
        'id' => 107,
        'lang' => 'PHP',
        'name' => 'Ratchet',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    108 => [
        'id' => 108,
        'lang' => 'PHP',
        'name' => 'Composer',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    109 => [
        'id' => 109
        'lang' => 'PHP',
        'name' => 'minify',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    110 => [
        'id' => 110,
        'lang' => 'PHP',
        'name' => 'Sentinel',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],

    //Python
    201 => [
        'id' => 201,
        'lang' => 'Python',
        'name' => 'Python',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    202 => [
        'id' => 202,
        'lang' => 'Python',
        'name' => 'Django',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    203 => [
        'id' => 203,
        'lang' => 'Python',
        'name' => 'Tensorflow',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    204 => [
        'id' => 204,
        'lang' => 'Python',
        'name' => 'Flask',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    205 => [
        'id' => 205,
        'lang' => 'Python',
        'name' => 'pip',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],
    206 => [
        'id' => 206,
        'lang' => 'Python',
        'name' => 'six',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    207 => [
        'id' => 207,
        'lang' => 'Python',
        'name' => 'NumPy',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    208 => [
        'id' => 208,
        'lang' => 'Python',
        'name' => 'pandas',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    209 => [
        'id' => 209,
        'lang' => 'Python',
        'name' => 'Plone',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    210 => [
        'id' => 210,
        'lang' => 'Python',
        'name' => 'bottle',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],
    
    //Ruby
    301 => [
        'id' => 301,
        'lang' => 'Ruby',
        'name' => 'Ruby',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    302 => [
        'id' => 302,
        'lang' => 'Ruby',
        'name' => 'Ruby on rails',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    303 => [
        'id' => 303,
        'lang' => 'Ruby',
        'name' => 'Gem',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    304 => [
        'id' => 304,
        'lang' => 'Ruby',
        'name' => 'bundler',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    305 => [
        'id' => 305,
        'lang' => 'Ruby',
        'name' => 'eRuby',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],
    306 => [
        'id' => 306,
        'lang' => 'Ruby',
        'name' => 'rspec-rails',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    307 => [
        'id' => 307,
        'lang' => 'Ruby',
        'name' => 'Awesome Print',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    308 => [
        'id' => 308,
        'lang' => 'Ruby',
        'name' => 'Kaminari',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    309 => [
        'id' => 309,
        'lang' => 'Ruby',
        'name' => 'HANAMI',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    310 => [
        'id' => 310,
        'lang' => 'Ruby',
        'name' => 'Sinatra',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],

    //Normal
    901 => [
        'id' => 901,
        'lang' => 'Normal',
        'name' => 'if',
        'barning' => 10,
        'priogress' => 10,
        'time' => 1,
    ],
    902 => [
        'id' => 902,
        'lang' => 'Normal',
        'name' => 'switch',
        'barning' => 20,
        'priogress' => 20,
        'time' => 1,
    ],
    903 => [
        'id' => 903,
        'lang' => 'Normal',
        'name' => 'while',
        'barning' => 30,
        'priogress' => 30,
        'time' => 1,
    ],
    904 => [
        'id' => 904,
        'lang' => 'Normal',
        'name' => 'for',
        'barning' => 40,
        'priogress' => 40,
        'time' => 1,
    ],
    905 => [
        'id' => 905,
        'lang' => 'Normal',
        'name' => 'foreach',
        'barning' => 50,
        'priogress' => 50,
        'time' => 1,
    ],

    // // PHP
    // 'php' => [
    //     '1-php' => '1-php',
    //     '2-php' => '2-php',
    //     '3-php' => '3-php',
    //     '4-php' => '4-php',
    //     '5-php' => '5-php',
    //     '6-php' => '6-php',
    //     '7-php' => '7-php',
    //     '8-php' => '8-php',
    //     '9-php' => '9-php',
    //     '10-php' => '10-php',
    // ],
    // // Python
    // 'python' => [
    //     '1-python' => '1-python',
    //     '2-python' => '2-python',
    //     '3-python' => '3-python',
    //     '4-python' => '4-python',
    //     '5-python' => '5-python',
    //     '6-python' => '6-python',
    //     '7-python' => '7-python',
    //     '8-python' => '8-python',
    //     '9-python' => '9-python',
    //     '10-python' => '10-python',
    // ],
    // // Ruby
    // 'ruby' => [
    //     '1-ruby' => '1-ruby',
    //     '2-ruby' => '2-ruby',
    //     '3-ruby' => '3-ruby',
    //     '4-ruby' => '4-ruby',
    //     '5-ruby' => '5-ruby',
    //     '6-ruby' => '6-ruby',
    //     '7-ruby' => '7-ruby',
    //     '8-ruby' => '8-ruby',
    //     '9-ruby' => '9-ruby',
    //     '10-ruby' => '10-ruby',
    // ],
    // // Normal
    // 'normal' => [
    //     '1-normal' => '1-normal',
    //     '2-normal' => '2-normal',
    //     '3-normal' => '3-normal',
    //     '4-normal' => '4-normal',
    //     '5-normal' => '5-normal',
    //     '6-normal' => '6-normal',
    //     '7-normal' => '7-normal',
    //     '8-normal' => '8-normal',
    //     '9-normal' => '9-normal',
    //     '10-normal' => '10-normal',
    // ],

];
