<?php

return [
    //1** => PHP, 2** => Python, 3** => Ruby, 9** => Normal

    //PHP
    101 => [
        'id' => 101,
        'lang' => 'PHP',
        'name' => 'PHP',
        'barning' => 5,
        'progress' => 5,
        'time' => 1,
    ],
    102 => [
        'id' => 102,
        'lang' => 'PHP',
        'name' => 'Symfony',
        'barning' => 10,
        'progress' => 10,
        'time' => 1,
    ],
    103 => [
        'id' => 103,
        'lang' => 'PHP',
        'name' => 'Laravel',
        'barning' => 15,
        'progress' => 15,
        'time' => 1,
    ],
    104 => [
        'id' => 104,
        'lang' => 'PHP',
        'name' => 'CakePHP',
        'barning' => 20,
        'progress' => 20,
        'time' => 1,
    ],
    105 => [
        'id' => 105,
        'lang' => 'PHP',
        'name' => 'FuelPHP',
        'barning' => 25,
        'progress' => 25,
        'time' => 1,
    ],
    106 => [
        'id' => 106,
        'lang' => 'PHP',
        'name' => 'WordPress',
        'barning' => 30,
        'progress' => 30,
        'time' => 1,
    ],
    107 => [
        'id' => 107,
        'lang' => 'PHP',
        'name' => 'Ratchet',
        'barning' => 35,
        'progress' => 35,
        'time' => 1,
    ],
    108 => [
        'id' => 108,
        'lang' => 'PHP',
        'name' => 'Composer',
        'barning' => 40,
        'progress' => 40,
        'time' => 1,
    ],
    109 => [
        'id' => 109,
        'lang' => 'PHP',
        'name' => 'minify',
        'barning' => 45,
        'progress' => 45,
        'time' => 1,
    ],
    110 => [
        'id' => 110,
        'lang' => 'PHP',
        'name' => 'Sentinel',
        'barning' => 50,
        'progress' => 50,
        'time' => 1,
    ],

    //Python
    201 => [
        'id' => 201,
        'lang' => 'Python',
        'name' => 'Python',
        'barning' => 5,
        'progress' => 5,
        'time' => 1,
    ],
    202 => [
        'id' => 202,
        'lang' => 'Python',
        'name' => 'Django',
        'barning' => 10,
        'progress' => 10,
        'time' => 1,
    ],
    203 => [
        'id' => 203,
        'lang' => 'Python',
        'name' => 'Tensorflow',
        'barning' => 15,
        'progress' => 15,
        'time' => 1,
    ],
    204 => [
        'id' => 204,
        'lang' => 'Python',
        'name' => 'Flask',
        'barning' => 20,
        'progress' => 20,
        'time' => 1,
    ],
    205 => [
        'id' => 205,
        'lang' => 'Python',
        'name' => 'pip',
        'barning' => 25,
        'progress' => 25,
        'time' => 1,
    ],
    206 => [
        'id' => 206,
        'lang' => 'Python',
        'name' => 'six',
        'barning' => 30,
        'progress' => 30,
        'time' => 1,
    ],
    207 => [
        'id' => 207,
        'lang' => 'Python',
        'name' => 'NumPy',
        'barning' => 35,
        'progress' => 35,
        'time' => 1,
    ],
    208 => [
        'id' => 208,
        'lang' => 'Python',
        'name' => 'pandas',
        'barning' => 40,
        'progress' => 40,
        'time' => 1,
    ],
    209 => [
        'id' => 209,
        'lang' => 'Python',
        'name' => 'Plone',
        'barning' => 45,
        'progress' => 45,
        'time' => 1,
    ],
    210 => [
        'id' => 210,
        'lang' => 'Python',
        'name' => 'bottle',
        'barning' => 50,
        'progress' => 50,
        'time' => 1,
    ],
    
    //Ruby
    301 => [
        'id' => 301,
        'lang' => 'Ruby',
        'name' => 'Ruby',
        'barning' => 5,
        'progress' => 5,
        'time' => 1,
    ],
    302 => [
        'id' => 302,
        'lang' => 'Ruby',
        'name' => 'Ruby on rails',
        'barning' => 10,
        'progress' => 10,
        'time' => 1,
    ],
    303 => [
        'id' => 303,
        'lang' => 'Ruby',
        'name' => 'Gem',
        'barning' => 15,
        'progress' => 15,
        'time' => 1,
    ],
    304 => [
        'id' => 304,
        'lang' => 'Ruby',
        'name' => 'bundler',
        'barning' => 20,
        'progress' => 20,
        'time' => 1,
    ],
    305 => [
        'id' => 305,
        'lang' => 'Ruby',
        'name' => 'eRuby',
        'barning' => 25,
        'progress' => 25,
        'time' => 1,
    ],
    306 => [
        'id' => 306,
        'lang' => 'Ruby',
        'name' => 'rspec-rails',
        'barning' => 30,
        'progress' => 30,
        'time' => 1,
    ],
    307 => [
        'id' => 307,
        'lang' => 'Ruby',
        'name' => 'Awesome Print',
        'barning' => 35,
        'progress' => 35,
        'time' => 1,
    ],
    308 => [
        'id' => 308,
        'lang' => 'Ruby',
        'name' => 'Kaminari',
        'barning' => 40,
        'progress' => 40,
        'time' => 1,
    ],
    309 => [
        'id' => 309,
        'lang' => 'Ruby',
        'name' => 'HANAMI',
        'barning' => 45,
        'progress' => 45,
        'time' => 1,
    ],
    310 => [
        'id' => 310,
        'lang' => 'Ruby',
        'name' => 'Sinatra',
        'barning' => 50,
        'progress' => 50,
        'time' => 1,
    ],

    //Normal
    901 => [
        'id' => 901,
        'lang' => 'Normal',
        'name' => 'if',
        'barning' => 5,
        'progress' => 5,
        'time' => 1,
    ],
    902 => [
        'id' => 902,
        'lang' => 'Normal',
        'name' => 'switch',
        'barning' => 10,
        'progress' => 10,
        'time' => 1,
    ],
    903 => [
        'id' => 903,
        'lang' => 'Normal',
        'name' => 'while',
        'barning' => 15,
        'progress' => 15,
        'time' => 1,
    ],
    904 => [
        'id' => 904,
        'lang' => 'Normal',
        'name' => 'for',
        'barning' => 20,
        'progress' => 20,
        'time' => 1,
    ],
    905 => [
        'id' => 905,
        'lang' => 'Normal',
        'name' => 'foreach',
        'barning' => 25,
        'progress' => 25,
        'time' => 1,
    ],

];
