<?php

return [
    //1** => PC, 2** => Drink,

    //PC
    101 => [
        'id' => 101,
        'name' => 'しょぼいPC',
        'type' => 'PC',
        'money' => 6000,
        'barning' => -10,
        'progress' => 10,
        'time' => 1,
        'explain' => '8年前のPC。もさもさの動作でもまだ使える。',
        'message' => '「動作がカクカク」',
    ],
    102 => [
        'id' => 102,
        'name' => 'ふつうのPC',
        'type' => 'PC',
        'money' => 12000,
        'barning' => -20,
        'progress' => 20,
        'time' => 1,
        'explain' => '6年前のPC。なかなかに冷却ファンがうるさい。',
        'message' => '「普通に動く」',
    ],
    103 => [
        'id' => 103,
        'name' => 'いいPC',
        'type' => 'PC',
        'money' => 24000,
        'barning' => -40,
        'progress' => 40,
        'time' => 1,
        'explain' => '去年のPC。なかなか働いてくれる。',
        'message' => '「すげぇ！なめらかだ！」',
    ],

    //Drink
    201 => [
        'id' => 201,
        'name' => 'コーヒー',
        'type' => 'Drink',
        'money' => 2800,
        'barning' => -10,
        'progress' => 0,
        'time' => 1,
        'explain' => 'これがなければ始まらない。',
        'message' => '「大人の苦み」',
    ],
    202 => [
        'id' => 202,
        'name' => 'RedBull',
        'type' => 'Drink',
        'money' => 5600,
        'barning' => -20,
        'progress' => 0,
        'time' => 1,
        'explain' => '窮地に立ったとき、これに手が伸びる。',
        'message' => '「頭に翼が生えたー」',
    ],
    203 => [
        'id' => 203,
        'name' => 'Monster',
        'type' => 'Drink',
        'money' => 11200,
        'barning' => -40,
        'progress' => 0,
        'time' => 1,
        'explain' => '最終兵器モンスター',
        'message' => '「カフェイン・・もっとカフェインを寄越せ・・・」',
    ],

    //Food
    301 => [
        'id' => 301,
        'name' => 'クッキー',
        'type' => 'Food',
        'money' => 2800,
        'barning' => 0,
        'progress' => 10,
        'time' => 1,
        'explain' => 'コーヒーとよく合う。',
        'message' => '「ぼりぼり」',
    ],
    
    302 => [
        'id' => 302,
        'name' => 'チョコ',
        'type' => 'Food',
        'money' => 5600,
        'barning' => 0,
        'progress' => 20,
        'time' => 1,
        'explain' => 'コーヒーととてもよく合う。',
        'message' => '「むしゃむしゃ」',
    ],

    303 => [
        'id' => 303,
        'name' => '焼肉',
        'type' => 'Food',
        'money' => 11200,
        'barning' => 0,
        'progress' => 40,
        'time' => 1,
        'explain' => 'ご褒美。食べすぎに注意。',
        'message' => '「じゅーじゅー」',
    ],

    //Drug
    401 => [
        'id' => 401,
        'name' => 'リポビタンD',
        'type' => 'Drug',
        'money' => 6000,
        'barning' => 10,
        'progress' => -10,
        'time' => 1,
        'explain' => '栄養ドリンク。頑張れる',
        'message' => '「もうひと頑張り」',
    ],

    402 => [
        'id' => 402,
        'name' => 'カフェインの錠剤',
        'type' => 'Drug',
        'money' => 12000,
        'barning' => -20,
        'progress' => 20,
        'time' => 1,
        'explain' => 'カフェイン中毒御用達。カフェイン補給用',
        'message' => '「あぁ/////これがなきゃ仕事はできねーよなぁ！///あぁぁぁぁぁ///////」',
    ],
    
    403 => [
        'id' => 403,
        'name' => '眠眠打破',
        'type' => 'Drug',
        'money' => 24000,
        'barning' => -40,
        'progress' => 40,
        'time' => 1,
        'explain' => '眠気が吹っ飛ぶ。徹夜用',
        'message' => '「ああぁぁぁ/////カフェイン様ありがとうございますぅ//////これで徹夜が出来るんですよぉ//////徹夜しちゃいますぅ////////」',
    ],
    
];
